#       _       _
#      | |     | |
#      | | ___ | |__
#  _   | |/ _ \| '_ \
# | |__| | (_) | |_) |
#  \____/ \___/|_.__/

price:
  job-change:
    vip: 1000
    vip+: 900
    mvip: 800
    mvip+: 700
    hvip: 600
    default: 1500
  quest-change:
    vip: 600
    vip+: 500
    mvip: 400
    mvip+: 300
    hvip: 200
    default: 750


